
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"] # Use crates implementation for memcpy, memset, etc.

[build]
target = "x86_64-astra_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
